import { TDictionary } from "./types/types";

export const hr: TDictionary = Object.freeze({
  Count: "Broj",
  Cancel: "Odustani",
  Save: "Spremi",
  Show: "Prikaži",
  "Show form": "Prikaži formu",
  Edit: "Uredi",
  Create: "Dodaj",
  Add: "Dodaj",
  Hide: "Sakrij",
  Delete: "Izbriši",
  Back: "Nazad",
  List: "Lista",
  "System setup": "Postavljanje sustava",
  "Download template": "Preuzmi predložak",
  OFF: "Isključi",
  ON: "Uključi",
  Customer: "Klijent",
  Caterer: "Ugostitelj",
  Customers: "Klijenti",
  Company: "Kompanija",
  "Created at": "Kreiran",
  "Updated at": "Ažuriran",
  "Created by": "Kreirao user",
  Status: "Status",
  Subscribe: "Pretplati",
  Unsubscribe: "Otkaži pretplatu",
  Informations: "Informacije",
  Contacts: "Kontakti",
  "Cash registers": "Uređaji",
  "Cash ragister": "Uređaj",
  Quotes: "Ponude",
  Invoices: "Računi",
  Search: "Pretraži",
  "Search by name or company": "Pretraži po imenu ili kompaniji",
  "Create new customer": "Kreiraj novog klijenta",
  "Customers list": "Lista klijenta",
  "All customers": "Svi klijenti",
  "Select partner": "Izaberi partnera",
  "Belongs to partner": "Pripada partneru",
  "Customer informations": "Informacije o klijentu",
  "Update :Name account's profile information": "Unesite podatke o klijentu :Name",
  "Assign partner": "Dodijeli partnera",
  Attachments: "Prilozi",
  Options: "Opcije",
  "Poa data": "Poslovni prostor",
  Items: "Artikli",
  "Paired with device": "Upareni uređaji",
  "Security element": "Sigurnosni element",
  "Set-up": "Postavljanje",
  Active: "Aktivan",
  Lead: "Bez tenanta",
  Suspended: "Suspendiran",
  Snoozed: "Odgođena suspenzija",
  "Set as resolved": "Označi kao riješeno",
  "Set as snoozed": "Odgodi suspenziju",
  "Set as suspended": "Postavi suspenziju",
  All: "Svi",
  Resolved: "Riješeno",
  "Enter first name": "Unesi ime",
  "Enter last name": "Unesi prezime",
  "Enter ID Card number": "Unesi br. osobne",
  "Enter one or more POA labels": "Unesi jednu ili više oznaka poslovnog prostora",
  "POA Labels": "Oznaka poslovnog prostora",
  "ID Card number": "Br. lične karte",
  "Upload items": "Učitavanje artikla",
  Upload: "Učitaj",
  "Create customer": "Kreiraj klijenta",
  "VAT payer": "Obveznik PDV-a",
  "Customer information": "Informacije o klijentu",
  "Insert accounts profile information.": "Unesite podatke o klijentu",
  "Fill in basic details needed for billing.": "Ispuni osnovne informacije potrebne za naplatu",
  "Delete customer": "Izbriši klijenta",
  "Sale channel": "Prodajni kanal",
  "First name": "Ime",
  "Last name": "Prezime",
  Address: "Adresa",
  "Email addresses": "Email adrese",
  "Additional address": "Dodatna adresa",
  "Additional address City": "Dodatna adresa - Grad",
  "Additional address Zip": "Dodatna adresa - Poštanski broj",
  "Additional address Region": "Dodatna adresa - Regija",
  "Additional address Name": "Dodatna adresa - Naziv kompanije",
  "Additional address Note": "Dodatna adresa - Nota",
  Country: "Država",
  Zip: "Zip",
  City: "Grad",
  "Company name": "Kompanija",
  Activity: "Djelatnost",
  "Activity type": "Tip djelatnosti",
  "Login as user": "Prijava kao korisnik",
  "Create tenant": "Kreiraj tenanta",
  "Delivery address": "Adresa za dostavu",
  "Delivery - First name": "Dostava - Ime",
  "Delivery - Last name": "Dostava - Prezime",
  "Delivery - Address": "Dostava - Adresa",
  "Delivery - Additional address": "Dostava - Dodatna adresa",
  "Delivery - Country": "Dostava - Država",
  "Delivery - Zip": "Dostava - Zip",
  "Delivery - City": "Dostava - Grad",
  "Delivery - Region": "Dostava - Region",
  "Delivery - Company name": "Dostava - Ime firme",
  "Delivery - Notes": "Dostava - Napomena",
  "Vat number": "OIB",
  VAT: "OIB",
  "Fiscal nubmer": "Fiskalni broj",
  Phone: "Mobilni telefon",
  "Phone number": "Mobilni telefon",
  Email: "Email",
  Grenke: "Grenke",
  "Company type": "Tip kompanije",
  "Company date": "Datum kompanije",
  "Company note": "Napomena kompanije",
  "Legal contact": "Pravni kontakt",
  Payment: "Plaćanje",
  Iban: "Iban",
  "Full Name": "Ime i prezime",
  "Iban name": "Iban ime",
  Note: "Napomena",
  "PCI / SID": "PCI / SDI",
  GDPR: "GDPR",
  Newsletter: "Newsletter",
  "Customer status": "Status klijenta",
  "Billing status": "Status naplate",
  "Tenant status": "Status tenanta",
  Phones: "Telefoni",
  Primary: "Primarni",
  "Company region": "Regija kompanije",
  "Set primary": "Postavi kao primarni",
  Actions: "Akcije",
  Yes: "Da",
  No: "Ne",
  "Vat number exists": "Klijent sa tim OIB-om već postoji",
  Administration: "Administracija",
  EINVOICE: "E-Račun",
  Warehouses: "Skladište",
  Packages: "Pretplate",
  Billing: "Uplate",
  Submit: "Potvrdi",
  "Cash register": "Blagajna",
  "Neosalon tenant - Create": "Neosalon tenant - Kreiraj",
  "Plus package": "Plus paket",
  "Select cash register": "Odaberi blagajnu",
  "Login to cash register": "Prijavi se na blagajnu",
  "Neosalon error": "Neosalon greška",
  Open: "Otvori",
  "Is active": "Aktivna",
  Name: "Naziv",
  Code: "Šifra",
  "There is no device": "Nema dostupnih uređaja",
  "Include email for system setup": "Pošalji email za postavljanje sustava",
  Users: "Korisnici",
  Devices: "Uređaji",
  "Log in": "Prijavi se",
  "Send temporary password": "Pošalji privremenu lozinku",
  Username: "Korisničko ime",
  Password: "Lozinka",
  "Submit note": "Spremi napomenu",
  Setup: "Postavljanje sustava",
  Pricelist: "Cjenik",
  "Generate password": "Generiraj lozinku",
  Additional: "Dodatna",
  Warned: "Upozoren",
  Subject: "Predmet",
  From: "Pošiljatelj",
  To: "Primatelj",
  Success: "Uspješno",
  Body: "Sadržaj",
  Dunning: "Upozorenja",
  "Email logs": "Email logovi",
  "All email logs": "Svi email logovi",
  "Sent to the customer": "Poslano korisniku",
  "Sent by the customer via cash register": "Korisnik poslao iz blagajne",
  "Status not found": "Status nije pronađen",
  Message: "Poruka",
  "Sent date": "Datum slanja",
  Sent: "Poslano",
  Received: "Zaprimljeno",
  Deliveries: "Isporuke",
});
