export const rs = Object.freeze({
  // Dashboard
  "Welcome to marketino administration": "Dobrodošli u Marketino administraciju",
  Start: "Kreni",
  Organisation: "Organizacija",
  "Company, Certificate Business premises": "Preduzeće, Certifikat Poslovni prostor",
  "Sales settings": "Prodajne postavke",
  "ss desc": "Asortiman, Način plaćanja, PDV",
  Clients: "Klijenti",
  "Client entry, Search clients": "Unos klijenta, Pretraži klijente",
  Reports: "Izvješća",
  "Daily report, Cross-section of the situation": "Dnevni izvještaj, Presek stanja",
  Settings: "Postavke",
  "Accounting, Accounts": "Računovodstvo, Računi",

  // Login
  "Forgot password": "Zaboravio sam lozinku",
  Username: "Korisničko ime",
  Password: "Lozinka",
  Login: "Prijava",
  "Remember me": "Zapamti me",

  // Organization
  "The unique mark of the payment device": "Jedinstvena oznaka naplatnog uređaja",
  "The name you want to give to your cash register, this information is not printed on the account or submitted to the Tax Administration":
    "Naziv koji želite dati svojoj kasi, ovaj podatak se ne ispisuje na računu niti se dostavlja Poreznoj upravi",
  Label: "Oznaka",
  Name: "Naziv",
  "Business premises": "Poslovni prostor",
  "Business premises where the payment device will be used": "Poslovni prostor unutar kojeg će se koristiti naplatni uređaj",
  Deposit: "Depozit",
  "The amount of cash deposit related to the individual payment device (cash register)":
    "Iznos gotovinskog depozita koji se odnosi na pojedinačni naplatni uređaj (kasa)",
  Save: "Sačuvaj",
  Add: "Dodaj",
  Delete: "Obriši",
  Description: "Opis",
  "The name and designation of the business premises are printed on the header of each issued invoice. You should provide information about the registered business premises":
    "Naziv i oznaka poslovnog prostora štampaju su na zaglavlju svake izdate fakture. Trebalo bi da odgovaraju podacima o registrovanom poslovnom prostoru",
  "The name and designation of the business premises are printed on the header of each issued invoice. They must match the data on the registered business premises":
    "Naziv i oznaka poslovnog prostora štampaju su na zaglavlju svake izdate fakture. Moraju da odgovaraju podacima o registrovanom poslovnom prostoru",
  Address: "Adresa",
  City: "Grad",
  "Postal code": "Poštanski broj",
  "Activity code": "Šifra delatnosti",
  "Type / Code of the activity performed in the business premises":
    "Vrsta / Šifra delatnosti koja se obavlja u poslovnom prostoru",
  "First and last name": "Ime i prezime",
  "It must be in the format /^[a-zd_.]+$/. Diacritics, capital letters, spaces and special characters are not allowed. Only lowercase letters a-z, numbers, and special characters _ and . and ,":
    "Mora biti u formatu /^[a-zd_.]+$/. Nisu dopušteni dijakritici, velika slova, razmaci niti posebni znakovi. Dopuštena su samo mala slova a-z, brojevi, i od specijalnih znakova _ i . i ,",
  "If the 'Name to print' field is not filled in, the first and last name are printed on the invoice printout":
    "Ukoliko polje 'Naziv za ispis' nije ispunjeno, ispisuje se ime i prezime na ispisa računa",
  "Print name": "Naziv za ispis",
  "The name of the person issuing the invoice as it will be printed on the issued invoice. You can enter any name, such as Marko, Kasir 1 and similar":
    "Ime lica koje izdaje račun kako će biti odštampano na izdatom računu. Možete uneti bilo koje ime, kao što su Marko, Kasir 1 i slično",
  "Vat number": "PIB",
  "Phone number": "Mobilni telefon",
  "Issued invoice": "Izdanom računu",
  Email: "Email",
  'The email that will be used to deliver the password or in case the user initiates the "I forgot my password" action':
    "Email koji će se koristiti za dostavu lozinke ili u slučaju da korisnik sam pokrene akciju “Zaboravio sam lozinku",
  "User type": "Vrsta korisnika",
  "The administrator has insight and can use all the benefits of the program, while the cashier does not have all the permissions":
    "Administrator ima uvid i može da koristi sve pogodnosti programa, dok kasir nema sve dozvole",
  Administrator: "Administrator",
  Cashier: "Kasir",
  Permissions: "Dozvole",
  "User permissions": "Dozvole korisnika",
  "Price change": "Promjena cijene",
  "Change of discount": "Promjena popusta",
  "Report settings": "Postavke izvješća",
  Activity: "Aktivnost",
  'The "Active" status for an individual user indicates the possibility of regular work with the program, while the "Inactive" status indicates the inability to work, regardless of the activity status of the device to which the inactive user is trying to log in':
    "Status „Aktivan“ za pojedinačnog korisnika ukazuje na mogućnost redovnog rada sa programom, dok status „Neaktivan“ označava nemogućnost rada, bez obzira na status aktivnosti uređaja na koji neaktivni korisnik pokušava da se prijavi",
  Active: "Aktivan",
  Inactive: "Neaktivan",
  "New payment device": "Novi naplatni uređaj",
  "Edit payment device": "Edit payment device",
  "New business premises": "Novi poslovni prostor",
  "Edit business premises": "Uredi poslovni prostor",
  "New user": "Novi korisnik",
  "Edit user": "Uredi korisnika",
  "Activity (NKD)": "Djelatnost (NKD)",
  Paired: "Uparena", // Uparena kasa
  "VAT obligation according to": "Obveza PDV-a po",
  'Choose what kind of relationship your company has with VAT. The option "By issued invoice" refers to entrepreneurs whose obligation to pay VAT arises when the invoice is issued (most often companies - d.o.o. or d.d.). The option "By billed invoice" refers to income tax payers whose VAT is calculated by billed invoices (most often turnover). Not liable for VAT - This option indicates companies':
    "Odaberite kakav odnos vaše preduzeće ima sa PDV-om. Opcija „Po izdanom računu“ odnosi se na preduzetnike čija obaveza plaćanja PDV-a nastaje prilikom izdavanja računa (najčešće firme – d.o.o. ili d.d.). Opcija „Po naplaćenom računu“ odnosi se na obveznike poreza na dohodak kod kojih se PDV obračunava po naplaćenim računima (najčešće promet). Nije obveznik PDV-a - Ova opcija označava preduzeća",
  "Subject to VAT": "Obaveznik PDV-a",
  "Charged invoice": "Naplaćenom računu",
  "Not subject to VAT": "Neobaveznik PDV-a",
  "Subject to VAT according to": "Obaveznik PDV-a po",
  "The unique internal code of your organization (company) is automatically assigned in the system. You may need this information when contacting customer support":
    "Jedinstvena interna oznaka vaše organizacije (kompanije) se automatski dodeljuje u sistemu. Ove informacije će vam možda trebati kada kontaktirate korisničku podršku",
  "Organization mark": "Oznaka organizacije",
  "According to the provisions of Article 34 of the VAT Ordinance, the fiscal device through which the turnover of food and beverage services for on-site consumption is recorded must have only the following options for recording the payment method: cash, transfer to account, voucher and others. For this type of payer, the caterer is unable to select card, instant payment and check when creating an invoice":
    "Prеmа odrеdbаmа člаnа 34. Prаvilnikа o PDV, fiskаlni urеđај prеko koјеg sе еvidеntirа promеt uslugе hrаnе i pićа zа konzumаciјu nа licu mеstа morа zа еvidеntirаnjе nаčinа plаćаnjа imаti isključivo slеdеćе opciје: gotovina, prenos na račun, vaučer i drugo. Za ovu vrstu obveznika ugostitelj onemogućen je odabir kartice, instant plaćanja i čeka prilikom izrade računa",
  Caterer: "Ugostitelj",
  "Telephone number of the responsible person": "Telefonski broj odgovornog lica",
  "Email address for delivery of invoices for use, as well as for other important information":
    "Email adresa za dostavu računa na korišćenje, kao i za druge važne informacije",
  "The tax identification number (PIB) of the enterprise or company will be printed on every invoice created":
    "Poreski identifikacioni broj (PIB) preduzeća ili kompanije ispisivaće se na svakom izrađenom računu",
  Owner: "Vlasnik",
  "The name of the company will be printed on each invoice": "Naziv preduzeca ili kompanije ispisivaće se na svakom računu",
  "Changing the type of account changes the VAT status of the company. For each item in your assortment, the VAT value will be ignored, and we advise you to correct the information and check the prices. Are you sure you want to change your company information? GO TO SETTINGS - REFRESH DATA TO APPLY CHANGES.":
    "Promjenom tipa računa mijenja se PDV status poduzeća. Za svaki artikal u vašem asortimanu zanemarit će se vrijednost PDV-a, a savjetujemo da ispravite podatke i provjerite cijene. Jeste li sigurni da želite promijeniti podatke opoduzeću? IDITE NA POSTAVKE - OSVEŽITE PODATKE DA BISTE PRIMENILI PROMENE.",
  "Name is a required field": "Naziv je obavezno polje.",
  "Organization owner is a required field": "Vlasnik organizacije je obavezno polje.",
  "Address is a required field": "Adresa je obavezno polje.",
  "City is a required field": "Grad je obavezno polje.",
  "Enter text here in accordance with the law, which will be printed on each issued invoice":
    "Ovde unesite tekst u skladu sa Zakonom koji će biti odštampan na svakom izdatom računu",
  "VAT exemption": "PDV oslobođenja",

  // Clients
  "Client type": "Vrsta lica",
  Physical: "Fizička",
  Legal: "Pravna",
  "Customer identification": "Identifikacija kupca",
  "Enter VAT": "Upišite PIB",
  "Optional client field": "Opcionalno polje kupca",
  Enter: "Upišite",
  "Person contact": "Kontakt osoba",
  Discount: "Popust",
  Note: "Napomena",
  Show: "Prikaži",
  more: "više",
  less: "manje",
  "Edit client": "Uredi klijenta",
  "New client": "Novi klijent",

  // Invoice settings
  "Enter the settings and data that will be applied when creating and printing the manual":
    "Unesite podešavanja i podatke koji će biti primjenjeni prilikom kreiranja i štampanja račnua",
  "Quick invoicing option": "Opcija brzog izdavanja računa",
  "After creating an account, start creating the next account": "Nakon izrade računa pokreni izradu sljedećeg računa",
  "Added text to print on each invoice header": "Dodatan tekst za štampanje na svakom zaglavlju računa",
  Row: "Redak",
  "Added text to print on each invoice footer": "Dodatan tekst za štampanje na svakom podnožju računa",
  "Choose options for preparing and sending data for posting to your accounting service":
    "Odaberite opcije pripreme i slanja podataka za knjiženje vašem računovodstvenom servisu",
  "Send automatically every month by e-mail": "Šalji automatski svaki mjesec e-mailom",
  "Accounting e-mail address": "E-mail adresa računovodstva",
  "Daily report": "Dnevni izvještaj",
  "Annual report - quarterly": "Godišnji izvještaj - kvartalni",
  "Daily report by item": "Dnevni izvještaj po artiklima",
  KPO: "KPO",
  "Monthly report": "Mesečni izvještaj",

  // Sales settings
  "Delete group": "Obriši grupu",
  "Edit group": "Uredi groupu",
  Group: "Grupa",
  "Selecting the group to which the article belongs is a mandatory field":
    "Odabir grupe kojoj pripada artikl je obavezno polje",
  "Item type cannot be changed. You have to delete the old one and add a new item":
    "Tip stavke se ne može promeniti. Morate izbrisati stari i dodati novi artikl",
  Type: "Tip",
  Product: "Proizvod",
  Service: "Usluga",
  "Unit of measure": "Jedinica mjere",
  Price: "Cijena",
  "The final selling price includes all taxes and fees": "Konačna prodajna cena, uključuje sve poreze i naknade",
  "Discount price": "Akcijska cijena",
  "The promotional price must be lower than the initial price": "Akcijska cena mora biti manja od inicijalne cene",
  "The discount percentage that will be automatically calculated for this product or service when creating an invoice":
    "Postotak popusta koji će se automatski obračunati na ovaj proizvod odnosno uslugu pri izradi računa",
  TAX: "PDV",
  "The rate of tax on a given value that is applied to the sale of a product or service":
    "Stopa poreza na datu vrednost koja se primenjuje na prodaju proizvoda ili usluge",
  Favorite: "Favorit",
  "GTIN/Barcode": "GTIN/Barkod",
  "By entering the barcode of the product and scanning it with the camera of your smartphone or device, you can select the item":
    "Unošenjem bar koda proizvoda i skeniranjem pomoću kamere pametnog telefona ili uređaja možete odabrati artikl",
  "The product or service code is informative information that does not affect the operation of the system":
    "Šifra proizvoda ili usluge je informativna informacija koja ne utiče na rad sistema",
  "Internal code": "Interna šifra",
  "Create new": "Kreiraj novi",
  "Group name": "Naziv grupe",
  "The name of the group within which you can market related products and services for easier and faster invoicing. For example, the hairdressing services of the group can include: men's haircuts, women's haircuts, children's haircuts, formal haircuts, etc.":
    "Naziv grupe u okviru koje možete plasirati srodne proizvode i usluge radi lakšeg i bržeg fakturisanja. Na primer, frizerskim uslugama grupe mogu biti: muške frizure, ženske frizure, dečije frizure, svečane frizure i sl.",
  "article(s)": "artikla",
  "Add group": "Dodaj grupu",
  "New article": "Novi artikl",
  "Edit article": "Uredi artikl",
  "New group": "Nova grupa",
  "Data import from Microsoft Excel": "Uvoz podataka iz Microsoft Excela",
  "Download the template here or print here": "Prenesite predložak ovdje ili pretisnite ovdje",
  Mistakes: "Grešaka",
  "Correct the following errors and reload the Excel spreadsheet":
    "Ispravite sljedeće greške i ponovno učitajte Excel tablicu",
  Mistake: "Greška",
  "Try again": "Pokušaj ponovno",
  "Congrats!": "Bravo!",
  "You have successfully imported": "Uspješno ste uvezli",
  "items in the assortment": "artikla u asortiman",
  Finish: "Završi",
  Import: "Uvezi",
  Export: "Izvezi",
  "Article type": "Vrsta artikla",
  "You can load data about your sales range from an Excel table into the cash register. This procedure is usually done when the user has a large number of articles to avoid typing the data, if the data can be prepared more simply in tabular form":
    "U blagajnu možete učitati podatke o vašim prodajnom asortimanu iz Excel tablice. Ovaj postupak se obično radi kad korisnik ima velik broj artikala da se izbjegne prekucavanje podataka, ako se podatke jednostavnije može pripremiti u tabličnom obliku",
  "Import data in four simple steps": "Uvoz podataka radite u četiri jednostavna koraka",
  "Download a blank Excel spreadsheet": "Preuzmite praznu Excel tablicu",
  "Click here to download": "Kliknite ovdje za preuzimanje",
  "Fill in the downloaded Excel table correctly": "Ispravno popunite preuzetu Excel tablicu",
  "The table must be filled in correctly to be able to import data. The description of what needs to be entered in which column of the table is shown below. Columns marked with an asterisk are required. Names of groups and products or services may contain letters, numbers and the following special characters: - . , & + ( ) ' % /. Before importing, the article group must already be present in the price list and the article name must be unique.":
    "Tablica mora biti ispravno popunjena da bi se mogao napraviti uvoz podataka. Opis što je potrebno upisati u koju kolonu tablice je prikazan u nastavku. Kolone označene sa zvjezdicom su obavezne. Nazivi grupa i proizvoda ili usluga smiju sadržavati slova, brojeve i sljedeće specijalne znakove: - . , & + ( ) ' % /. Grupa artikla prije uvoza mora biti već prisutna u cjeniku i naziv artikla mora biti jedinstven.",
  "Upload the completed template": "Učitajte ispunjeni predložak",
  "After filling in the table, save it to your computer and then mark it for loading using the file selection action.":
    "Nakon što popunite tablicu, spremite je na svoje računalo te je potom koristeći akciju za odabir datoteke označite za učitavanje.",
  "Import data": "Uvezite podatke",
  "Run 'Import Data' to start loading the data.": "Pokrenute 'Uvezi podatke' da se podaci započnu učitavati.",

  //
  Count: "Broj",
  Cancel: "Odustani",
  "Show form": "Prikaži formu",
  Edit: "Uredi",
  Create: "Dodaj",
  Hide: "Sakrij",
  Back: "Nazad",
  List: "Lista",
  "System setup": "Postavljanje sustava",
  "Download template": "Preuzmi predložak",
  OFF: "Isključi",
  ON: "Uključi",
  Customer: "Klijent",
  Customers: "Klijenti",
  Company: "Kompanija",
  "Created at": "Kreiran",
  "Updated at": "Ažuriran",
  "Created by": "Kreirao user",
  Status: "Status",
  Subscribe: "Pretplati",
  Unsubscribe: "Otkaži pretplatu",
  Informations: "Informacije",
  Contacts: "Kontakti",
  "Cash registers": "Uređaji",
  "Cash ragister": "Uređaj",
  Quotes: "Ponude",
  Invoices: "Računi",
  Search: "Pretraži",
  "Search by name or company": "Pretraži po imenu ili kompaniji",
  "Create new customer": "Kreiraj novog klijenta",
  "Customers list": "Lista klijenta",
  "All customers": "Svi klijenti",
  "Select partner": "Izaberi partnera",
  "Belongs to partner": "Pripada partneru",
  "Customer informations": "Informacije o klijentu",
  "Update :Name account's profile information": "Unesite podatke o klijentu :Name",
  "Assign partner": "Dodijeli partnera",
  Attachments: "Prilozi",
  Options: "Opcije",
  "Poa data": "Poslovni prostor",
  Items: "Artikli",
  "Paired with device": "Upareni uređaji",
  "Security element": "Sigurnosni element",
  "Set-up": "Postavljanje",
  Lead: "Bez tenanta",
  Suspended: "Suspendiran",
  Snoozed: "Odgođena suspenzija",
  "Set as resolved": "Označi kao riješeno",
  "Set as snoozed": "Odgodi suspenziju",
  "Set as suspended": "Postavi suspenziju",
  All: "Svi",
  Resolved: "Riješeno",
  "Enter first name": "Unesi ime",
  "Enter last name": "Unesi prezime",
  "Enter ID Card number": "Unesi br. osobne",
  "Enter one or more POA labels": "Unesi jednu ili više oznaka poslovnog prostora",
  "POA Labels": "Oznaka poslovnog prostora",
  "ID Card number": "Br. lične karte",
  "Upload items": "Učitavanje artikla",
  Upload: "Učitaj",
  "Create customer": "Kreiraj klijenta",
  "VAT payer": "Obveznik PDV-a",
  "Customer information": "Informacije o klijentu",
  "Insert accounts profile information.": "Unesite podatke o klijentu",
  "Fill in basic details needed for billing.": "Ispuni osnovne informacije potrebne za naplatu",
  "Delete customer": "Izbriši klijenta",
  "Sale channel": "Prodajni kanal",
  "First name": "Ime",
  "Last name": "Prezime",
  "Email addresses": "Email adrese",
  "Additional address": "Dodatna adresa",
  "Additional address City": "Dodatna adresa - Grad",
  "Additional address Zip": "Dodatna adresa - Poštanski broj",
  "Additional address Region": "Dodatna adresa - Regija",
  "Additional address Name": "Dodatna adresa - Naziv kompanije",
  "Additional address Note": "Dodatna adresa - Nota",
  Country: "Država",
  Zip: "Zip",
  "Company name": "Kompanija",
  "Activity type": "Tip djelatnosti",
  "Login as user": "Prijava kao korisnik",
  "Create tenant": "Kreiraj tenanta",
  "Delivery address": "Adresa za dostavu",
  "Delivery - First name": "Dostava - Ime",
  "Delivery - Last name": "Dostava - Prezime",
  "Delivery - Address": "Dostava - Adresa",
  "Delivery - Additional address": "Dostava - Dodatna adresa",
  "Delivery - Country": "Dostava - Država",
  "Delivery - Zip": "Dostava - Zip",
  "Delivery - City": "Dostava - Grad",
  "Delivery - Region": "Dostava - Region",
  "Delivery - Company name": "Dostava - Ime firme",
  "Delivery - Notes": "Dostava - Napomena",
  "Fiscal nubmer": "Fiskalni broj",
  Phone: "Mobilni telefon",
  Grenke: "Grenke",
  "Company type": "Tip kompanije",
  "Company date": "Datum kompanije",
  "Company note": "Napomena kompanije",
  "Legal contact": "Pravni kontakt",
  Payment: "Plaćanje",
  Iban: "Iban",
  "Full Name": "Ime i prezime",
  "Iban name": "Iban ime",
  "PCI / SID": "PCI / SDI",
  GDPR: "GDPR",
  Newsletter: "Newsletter",
  "Customer status": "Status klijenta",
  "Billing status": "Status naplate",
  "Tenant status": "Status tenanta",
  Phones: "Telefoni",
  Primary: "Primarni",
  "Company region": "Regija kompanije",
  "Set primary": "Postavi kao primarni",
  Actions: "Akcije",
  Yes: "Da",
  No: "Ne",
  "Vat number exists": "Klijent sa tim OIB-om već postoji",
  Administration: "Administracija",
  EINVOICE: "E-Račun",
  Warehouses: "Skladište",
  Packages: "Pretplate",
  Billing: "Uplate",
  Submit: "Potvrdi",
  "Cash register": "Blagajna",
  "Neosalon tenant - Create": "Neosalon tenant - Kreiraj",
  "Plus package": "Plus paket",
  "Select cash register": "Odaberi blagajnu",
  "Login to cash register": "Prijavi se na blagajnu",
  "Neosalon error": "Neosalon greška",
  Open: "Otvori",
  "Is active": "Aktivna",
  Code: "Šifra",
  "There is no device": "Nema dostupnih uređaja",
  "Include email for system setup": "Pošalji email za postavljanje sustava",
  Users: "Korisnici",
  Devices: "Uređaji",
  "Log in": "Prijavi se",
  "Send temporary password": "Pošalji privremenu lozinku",
  "Submit note": "Spremi napomenu",
  Setup: "Postavljanje sustava",
  Pricelist: "Cjenik",
  "Generate password": "Generiraj lozinku",
  Additional: "Dodatna",
  Warned: "Upozoren",
  Warning: "Upozorenje",
  Subject: "Predmet",
  From: "Pošiljatelj",
  To: "Primatelj",
  Success: "Uspješno",
  Body: "Sadržaj",
  Dunning: "Upozorenja",
  "Email logs": "Email logovi",
  "All email logs": "Svi email logovi",
  "Sent to the customer": "Poslano korisniku",
  "Sent by the customer via cash register": "Korisnik poslao iz blagajne",
  "Status not found": "Status nije pronađen",
  Message: "Poruka",
  "Sent date": "Datum slanja",
  Sent: "Poslano",
  Received: "Zaprimljeno",
  Deliveries: "Isporuke",
  Choose: "Odaberi",
});
